-- 020_role_permissions_seed.sql
-- Seed structured role permissions (Signatures / Visibility / Notifications / Progress).
-- Safe to re-run; only updates the named system roles.

UPDATE role_definitions SET permissions = '{"all":true}'::jsonb WHERE name = 'executive';
UPDATE role_definitions SET permissions = '{"all":true}'::jsonb WHERE name = 'ops_manager';
UPDATE role_definitions SET permissions = '{"sign.trust_pm":true,"view.tab_overview":true,"view.tab_plan_layout":true,"view.tab_design_proposal":true,"view.tab_construction":true,"view.tab_millwork":true,"view.tab_shelving":true,"view.tab_ceiling":true,"view.tab_image":true,"view.tab_decoration":true,"view.pf":true,"view.po":true,"view.production_board":true,"view.prices":true,"progress.finalization":true,"progress.construction":true,"progress.production":true,"progress.delivery":true,"notify.approval_request":true,"notify.approval_complete":true,"notify.revision":true,"notify.hold_t":true}'::jsonb WHERE name = 'trustlines_pm';
UPDATE role_definitions SET permissions = '{"sign.client_pm":true,"view.tab_overview":true,"view.tab_plan_layout":true,"view.tab_design_proposal":true,"view.tab_construction":true,"view.tab_millwork":true,"view.tab_shelving":true,"view.tab_ceiling":true,"view.tab_image":true,"view.tab_decoration":true,"view.pf":true,"view.po":true,"view.production_board":true,"view.prices":true,"progress.finalization":true,"progress.construction":true,"progress.production":true,"progress.delivery":true,"notify.approval_request":true,"notify.approval_complete":true,"notify.ready":true}'::jsonb WHERE name = 'tlines_pm';
UPDATE role_definitions SET permissions = '{"sign.trust_pm":true,"view.tab_overview":true,"view.tab_plan_layout":true,"view.tab_design_proposal":true,"view.tab_construction":true,"view.tab_millwork":true,"view.tab_shelving":true,"view.tab_ceiling":true,"view.tab_image":true,"view.tab_decoration":true,"view.pf":true,"view.po":true,"view.production_board":true,"view.prices":true,"progress.finalization":true,"progress.construction":true,"progress.production":true,"progress.delivery":true,"notify.approval_request":true}'::jsonb WHERE name = 'project_manager';
UPDATE role_definitions SET permissions = '{"sign.general_manager":true,"view.tab_overview":true,"view.tab_plan_layout":true,"view.tab_design_proposal":true,"view.tab_construction":true,"view.tab_millwork":true,"view.tab_shelving":true,"view.tab_ceiling":true,"view.tab_image":true,"view.tab_decoration":true,"view.pf":true,"view.po":true,"view.production_board":true,"view.prices":true,"progress.finalization":true,"progress.construction":true,"progress.production":true,"progress.delivery":true,"notify.approval_request":true,"notify.hold_t":true,"notify.payment":true}'::jsonb WHERE name = 'general_manager';
UPDATE role_definitions SET permissions = '{"sign.production_millwork":true,"sign.production_ceiling":true,"view.tab_overview":true,"view.tab_millwork":true,"view.tab_shelving":true,"view.tab_ceiling":true,"view.tab_image":true,"view.tab_decoration":true,"view.pf":true,"view.po":true,"view.production_board":true,"progress.production":true,"progress.delivery":true,"notify.approval_request":true}'::jsonb WHERE name = 'production_manager';
UPDATE role_definitions SET permissions = '{"sign.production_millwork":true,"view.tab_overview":true,"view.tab_millwork":true,"view.tab_shelving":true,"view.pf":true,"view.po":true,"view.production_board":true,"progress.production":true,"notify.approval_request":true}'::jsonb WHERE name = 'pm_millwork';
UPDATE role_definitions SET permissions = '{"sign.production_ceiling":true,"view.tab_overview":true,"view.tab_ceiling":true,"view.tab_image":true,"view.tab_decoration":true,"view.pf":true,"view.po":true,"view.production_board":true,"progress.production":true,"notify.approval_request":true}'::jsonb WHERE name = 'pm_ceiling';
UPDATE role_definitions SET permissions = '{"sign.accountant":true,"view.tab_overview":true,"view.po":true,"view.pf":true,"view.prices":true,"view.production_board":true,"progress.production":true,"progress.delivery":true,"notify.payment":true,"notify.approval_request":true}'::jsonb WHERE name = 'accountant';
UPDATE role_definitions SET permissions = '{"sign.accountant":true,"view.tab_overview":true,"view.po":true,"view.pf":true,"view.prices":true,"view.production_board":true,"progress.production":true,"progress.delivery":true,"notify.payment":true}'::jsonb WHERE name = 'accounting';
UPDATE role_definitions SET permissions = '{"view.tab_overview":true,"view.production_board":true,"progress.production":true,"progress.delivery":true}'::jsonb WHERE name = 'qc_responsible';
UPDATE role_definitions SET permissions = '{"view.tab_overview":true,"view.production_board":true,"progress.delivery":true,"notify.ready":true}'::jsonb WHERE name = 'logistics';
